title: Jayde Aufrecht # your name (or website title) here
logo: "/images/Aufrecht_Jayde.png" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data Scientist with 6+ years post-graduate work designing, conducting, and analyzing experiments. 
  <br><br>
   PhD in Energy Science and Engineering.
  <br><br>
  Domain knowledge in biology, environmental science, and energy systems.
  <br><br>
  <a href="https://www.linkedin.com/in/jayde-aufrecht/">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: G-3X74KBEQJF # your Google Analytics tracking ID here
